### ISSUE TITLE
Query String parameters should be URL encoded

### ISSUE THREAD

**Issue by wmbest2** [vokalinteractive/VOKMockUrlProtocol#12]

**Comment by vokal-isaac** [comment]
After discussion, it sounds like we've settled on leaving the path alone (save for replacing `/` and `:` with `-`) and having the keys and values in the query string be URL-encoded.

**Comment by wmbest2** [comment]
What was the issue with : again?

**Comment by vokal-isaac** [comment]
`:` was the path component separator used in Mac OS before OS X, so some applications (potentially including Finder) *really* don't like it when file names contain `:`.

**Comment by vokal-isaac** [comment]
Resolved by #17.
