### ISSUE TITLE
JSON should be handled in a full-depth manner

### ISSUE THREAD

**Issue by wmbest2** [vokalinteractive/VOKMockUrlProtocol#13]
@vokal-isaac Do you have any thoughts on using http://en.wikipedia.org/wiki/Bencode

Here is another resource I found as well as a Java library that would make this super simple on my end
https://github.com/pxqr/bencoding 
https://github.com/nicogiard/pisteur/blob/master/app/utils/BEncode.java

**Comment by vokal-isaac** [comment]
Resolved by #17.
